default:
  image: ${NEXUS_GROUP_REGISTRY}/maven:3.6-jdk-8

workflow:
  rules:
    - if: $CI_COMMIT_TAG

stages:
  - build
  - test
  - push

build:
  stage: build
  tags: [env-dev]
  script:
    - mvn -DskipTests package
    - cp target/*.jar docker/carts
  artifacts:
    expire_in: 2 hrs
    paths: 
      - ${CI_PROJECT_DIR}/docker/carts

test:
  stage: test
  tags: [env-dev]
  script:
    - mvn -q test
  needs: 
    - job: build
      artifacts: true

push:
  stage: push
  tags: [env-dev]
  image:
    name: ${NEXUS_GROUP_REGISTRY}/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker && echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
    - /kaniko/executor
      --build-arg "COMMIT=${CI_COMMIT_SHORT_SHA}"
      --build-arg "BUILD_DATE=${CI_JOB_STARTED_AT}"
      --context "${CI_PROJECT_DIR}/docker/carts"
      --dockerfile "${CI_PROJECT_DIR}/docker/carts/Dockerfile"
      --destination "${NEXUS_RELEASE_REGISTRY}/boutique/carts:${CI_COMMIT_TAG}"
      --registry-certificate ${NEXUS_RELEASE_REGISTRY}=${TRUSTED_CERTIFICATES}
      --registry-certificate ${NEXUS_GROUP_REGISTRY}=${TRUSTED_CERTIFICATES}
      --registry-mirror ${NEXUS_GROUP_REGISTRY}
