inventory:
  # ansible inventory structure
  # every host mentioned in this section must be specified in the hosts: section
  all:
    children:
      gitlab:
        hosts:
          gitlab11:
      runner:
        hosts:
          gitlab11:
      nexus:
        hosts:
          nexus11:

network: 
  name: instances
  subnets:
    subnet-a:
      zone: ru-central1-a 
      subnets: [192.168.0.0/24]
    subnet-b:
      zone: ru-central1-b 
      subnets: [192.168.1.0/24] 
# hosts specification
# every host must have defined name, cpu, memory, disk, public_ip
hosts:
  gitlab11:
    name: gitlab11
    cpu: 2
    memory: 4096
    disk: 40
    subnet: subnet-a
    public_ip: true
  nexus11:
    name: nexus11
    cpu: 2
    memory: 4096
    disk: 40
    subnet: subnet-b
    public_ip: true