certsSecretName: defaultcertificates
envVars:
  - name: CI_SERVER_TLS_CA_FILE
    value: /home/gitlab-runner/.gitlab-runner/certs/ru-central1.internal.crt
  - name: CONFIG_FILE
    value: /home/gitlab-runner/.gitlab-runner/config.toml
runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        image = "ubuntu:20.04"
        privileged = true
      [[runners.kubernetes.volumes.empty_dir]]
        name = "docker-certs"
        mount_path = "/certs/client"
        medium = "Memory"
      [[runners.kubernetes.volumes.empty_dir]]
        name = "dind-storage"
        mount_path = "/var/lib/docker"
      [[runners.kubernetes.volumes.host_path]]
        name = "hostpath-modules"
        mount_path = "/lib/modules"
        read_only = true
        host_path = "/lib/modules"
      [[runners.kubernetes.volumes.host_path]]
        name = "hostpath-cgroup"
        mount_path = "/sys/fs/cgroup"
        host_path = "/sys/fs/cgroup"
rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["list","get","watch","create","delete"]
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["list","get","watch","create","delete"]
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["list","get","watch","create","delete"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["list","get","watch","create","delete"]
    - apiGroups: [""]
      resources: ["pods/exec"]
      verbs: ["create"]
    - apiGroups: [""]
      resources: ["pods/log"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["pods/attach"]
      verbs: ["list","get","create","delete","update"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["list","get","create","delete","update"]
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["list","get","create","delete","update"]