default:
  image: docker:20.10.16
  tags:
  - infrastructure
  before_script:
    - mkdir -p ${HOME}/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  
stages:
  - build

build:
  stage: build
  script:
    - docker build --no-cache ./build/ -t ${NEXUS_REGISTRY}/builder/builder
    - docker push ${NEXUS_REGISTRY}/builder/builder
