workflow:
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
      changes:
      - builder/**/*
default:
  image: ${NEXUS_GROUP_REGISTRY}/docker:20.10.16
  tags:
  - infrastructure
  before_script:
    - mkdir -p ${HOME}/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  
stages:
  - build

build:
  stage: build
  script:
    - docker build ./builder/ -t ${NEXUS_RELEASE_REGISTRY}/infrastructure/builder:latest -t ${NEXUS_RELEASE_REGISTRY}/infrastructure/builder:${CI_PIPELINE_IID}
    - docker push ${NEXUS_RELEASE_REGISTRY}/infrastructure/builder:${CI_PIPELINE_IID}
    - docker push ${NEXUS_RELEASE_REGISTRY}/infrastructure/builder:latest || true