default:
  image: docker:20.10.16
  tags:
  - infrastructure
  
stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build --no-cache ./build/ -t builder

push:
  stage: push
  script:
    - echo docker push
