default:
  image: maven:3.6-jdk-11
  before_script:
    - chmod +x ./scripts/*
    - ls -la /certs/client
    - mkdir -p ${HOME}/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 0
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - build

build-a:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: build
  script:
    - sleep 60
    - docker info


build-package:
  stage: build
  script:
    - GROUP=weaveworksdemos COMMIT=test ./scripts/build.sh
  artifacts:
    expire_in: 2 hrs
    paths: 
      - ${CI_PROJECT_DIR}/docker/carts
      
build-image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: build
  script:
    - sleep 60
    - docker info
    - docker build --build-arg COMMIT=test -t carts ${CI_PROJECT_DIR}/docker/carts
  needs: 
    - job: build-package
      artifacts: true