default:
  image: docker.io/maven:3.6-jdk-11

workflow:
  rules:
    - if: $CI_COMMIT_TAG

stages:
  - build

build-package:
  stage: build
  tags: [dev]
  script:
    - mvn -DskipTests package
    - cp target/*.jar docker/carts
  artifacts:
    expire_in: 2 hrs
    paths: 
      - ${CI_PROJECT_DIR}/docker/carts
      
build:
  stage: build
  tags: [dev]
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker && echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
    - /kaniko/executor
      --insecure
      --build-arg "COMMIT=${CI_COMMIT_SHORT_SHA}"
      --build-arg "BUILD_DATE=${CI_JOB_STARTED_AT}"
      --context "${CI_PROJECT_DIR}/docker/carts"
      --dockerfile "${CI_PROJECT_DIR}/docker/carts/Dockerfile"
      --destination "${NEXUS_REGISTRY}/boutique/carts:${CI_COMMIT_TAG}"
  needs: 
    - job: build-package
      artifacts: true
