nexus_admin_password: "{{ NEXUS_ADMIN_PASSWORD }}"
nexus_public_hostname: 'nexus-lab'
httpd_setup_enable: false
nexus_privileges:
  - name: all-repos-read
    description: 'Read & Browse access to all repos'
    repository: '*'
    actions:
      - read
      - browse
  - name: company-project-deploy
    description: 'Deployments to company-project'
    repository: company-project
    actions:
      - add
      - edit
nexus_roles:
  - id: Gitlab # maps to the LDAP group
    name: gitlab
    description: All developers
    privileges:
      - nx-search-read
      - all-repos-read
      - company-project-deploy
      - nx-repository-admin-*-*-edit
      - nx-repository-view-*-*-*
    roles: []
nexus_local_users:
  - username: gitlab # used as key to update
    first_name: Gitlab
    last_name: CI
    email: support@company.com
    password: "{{ NEXUS_GITLAB_PASSWORD }}"
    roles:
      - Gitlab
nexus_scheduled_tasks:
  - name: compact-blobstore
    cron: '0 0 22 * * ?'
    typeId: blobstore.compact
    taskProperties:
      blobstoreName: 'company-artifacts'
nexus_config_docker: true

nexus_repos_docker_hosted:
  - name: docker-release
    http_port: 9079
    v1_enabled: True
  - name: docker-snapshots
    http_port: 9080
    v1_enabled: True
    cleanup_policies:
    - docker_snapshots_cleanup


nexus_repos_docker_group:
  - name: docker-group
    http_port: "{{ nexus_docker_group_port }}"
    v1_enabled: True
    member_repos:
      - docker-release
      - docker-snapshots
      - docker-proxy

nexus_repos_cleanup_policies:
  - name: docker_snapshots_cleanup
    format: docker
    mode:
    notes: "Cleaning Snapshots Repository"
    criteria:
      lastBlobUpdated: 2  # Optional
