workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"

default:
  before_script:
    - |
        mkdir -p /kaniko/.docker && echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
        if [ -n "$CI_COMMIT_TAG" ]; then 
          export TAG=${CI_COMMIT_TAG};
          export REGISTRY=${NEXUS_RELEASE_REGISTRY}; 
        else 
          export TAG=${CI_COMMIT_SHORT_SHA};
          export REGISTRY=${NEXUS_SNAPSHOTS_REGISTRY}; 
        fi

stages:
  - test
  - push

test:
  stage: test
  tags: [env-dev]
  image:
    name: node:10-alpine
  script:
    - yarn install
    - yarn test

push:
  stage: push
  tags: [env-dev]
  image:
    name: ${NEXUS_GROUP_REGISTRY}/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker && echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
    - /kaniko/executor
      --build-arg "COMMIT=${CI_COMMIT_SHORT_SHA}"
      --build-arg "BUILD_DATE=${CI_JOB_STARTED_AT}"
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${REGISTRY}/boutique/front-end:${TAG}"
      --registry-certificate ${REGISTRY}=${TRUSTED_CERTIFICATES}
      --registry-certificate ${NEXUS_GROUP_REGISTRY}=${TRUSTED_CERTIFICATES}
      --registry-mirror ${NEXUS_GROUP_REGISTRY}