workflow:
  rules:
    - if: $CI_COMMIT_TAG

default:
  image: golang:1.7

before_script:
  - mkdir -p $GOPATH/src/github.com/microservices-demo/
  - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/microservices-demo/payment
  
stages:
  - build
  - test
  - push

build:
  stage: build
  tags: [env-dev]
  script:
    - go get -u github.com/FiloSottile/gvt
    - gvt restore
    - cd $GOPATH/src/github.com/microservices-demo/payment/cmd/paymentsvc
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ${CI_PROJECT_DIR}/app
  artifacts:
    expire_in: 2 hrs
    paths: 
      - ${CI_PROJECT_DIR}/app

test:
  stage: test
  tags: [env-dev]
  script:
    - go get -u github.com/FiloSottile/gvt
    - gvt restore
    - cd $GOPATH/src/github.com/microservices-demo/payment/
    - go test -v -covermode=count -coverprofile=coverage.out

push:
  stage: push
  tags: [env-dev]
  image:
    name: ${NEXUS_GROUP_REGISTRY}/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker && echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
    - /kaniko/executor
      --build-arg "COMMIT=${CI_COMMIT_SHORT_SHA}"
      --build-arg "BUILD_DATE=${CI_JOB_STARTED_AT}"
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/payment/Dockerfile"
      --destination "${NEXUS_RELEASE_REGISTRY}/boutique/payment:${CI_COMMIT_TAG}"
      --registry-certificate ${NEXUS_RELEASE_REGISTRY}=${TRUSTED_CERTIFICATES}
      --registry-certificate ${NEXUS_GROUP_REGISTRY}=${TRUSTED_CERTIFICATES}
      --registry-mirror ${NEXUS_GROUP_REGISTRY}
