workflow:
  rules:
    - if: $CI_COMMIT_TAG

stages:
  - build
   
build-payment:
  stage: build
  tags: [dev]
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker && echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
    - /kaniko/executor
      --insecure
      --build-arg "COMMIT=${CI_COMMIT_SHORT_SHA}"
      --build-arg "BUILD_DATE=${CI_JOB_STARTED_AT}"
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/payment/Dockerfile"
      --destination "${NEXUS_REGISTRY}/boutique/payment:${CI_COMMIT_TAG}"

