workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
image:
  name: "$NEXUS_GROUP_REGISTRY/infrastructure/builder:latest"
  entrypoint: [""]

default:
  before_script:
    - source /app/scripts/lib.sh

stages:
  - deploy

deploy:
  stage:
    deploy
  tags: [env-prod]
  script:
  - deploy_boutique
