{
 "title": "Boutique Analytics",
 "tags": [ "boutique" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "# Orders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_duration_seconds_count{service=\"orders\",method=\"POST\"}"
    }
   ]
  },
  {
   "title": "Projected number of orders per day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_count{service=\"orders\",method=\"POST\"}[1h]) *24*60*60"
    }
   ]
  },
  {
   "title": "# Logins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_duration_seconds_count{service=\"user\", route=\"login\",status_code=\"200\"}"
    }
   ]
  }
 ]
}