inventory:
  # ansible inventory structure
  # every host mentioned in this section must be specified in the params: section
  all:
    children:
      k8s_cluster:
        children:
          kube_node:
            hosts:
              worker-prod21:  
              worker-prod22:
          kube_control_plane:
            hosts:
              master-prod23:
          etcd:
            hosts:
              master-prod23: 

runner:
  enabled: true
  name: prod-runner
  namespace: prod-runner
  helm_values: 
    - runner/values.yml

# hosts specification
# every host must have defined name, cpu, memory, disk, public_ip
hosts:
  worker-prod21:
    name: worker-prod21
    cpu: 2
    memory: 4096
    disk: 40
    subnet: prod-a
    public_ip: true
  worker-prod22:
    name: worker-prod22
    cpu: 2
    memory: 4096
    disk: 40
    subnet: prod-b
    public_ip: true
  master-prod23:
    name: master-prod23
    cpu: 2
    memory: 4096
    disk: 40
    subnet: prod-b
    public_ip: true