workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "/^env-.*/"
    - if: $CI_COMMIT_BRANCH =~ "/^env-.*/"  && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA != '0000000000000000000000000000000000000000'
image:
  name: "$NEXUS_GROUP_REGISTRY/infrastructure/builder:latest"
  entrypoint: [""]
variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

.terraform:plan: 
  stage: plan
  environment:
    name: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

.terraform:apply: 
  stage: apply
  environment:
    name: "${CI_COMMIT_REF_NAME}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.ansible:prepare: 
  stage: prepare
  environment:
    name: "${CI_COMMIT_REF_NAME}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.ansible:k8s: 
  stage: k8s
  environment:
    name: "${CI_COMMIT_REF_NAME}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.ansible:runner: 
  stage: runner
  environment:
    name: "${CI_COMMIT_REF_NAME}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.ansible:monitoring: 
  stage: monitoring
  environment:
    name: "${CI_COMMIT_REF_NAME}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.terraform:destroy: 
  stage: other
  when: manual
  environment:
    name: "${CI_COMMIT_REF_NAME}"

.terraform:status: 
  stage: other
  when: manual
  environment:
    name: "${CI_COMMIT_REF_NAME}"