image:
  name: "$NEXUS_GROUP_REGISTRY/infrastructure/builder:latest"
  entrypoint: [""]
variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"
  TF_VAR_ENV: ${ENV}
  TF_VAR_config: "${CI_PROJECT_DIR}/envs/${ENV}/config.yml"
  TF_VAR_ansible_inventory: "${CI_PROJECT_DIR}/envs/${ENV}/inventory.yml"
  ENV_PATH: ${CI_PROJECT_DIR}/envs/${ENV}

.terraform:plan: 
  stage: plan
  environment:
    name: $ENV

.terraform:apply: 
  stage: apply
  when: manual
  environment:
    name: $ENV

.ansible:prepare: 
  stage: prepare
  when: manual
  environment:
    name: $ENV

.ansible:k8s: 
  stage: k8s
  when: manual
  environment:
    name: $ENV

.ansible:runner: 
  stage: runner
  when: manual
  environment:
    name: $ENV

.ansible:monitoring: 
  stage: monitoring
  when: manual
  environment:
    name: $ENV

.terraform:destroy: 
  stage: other
  when: manual
  environment:
    name: $ENV

.terraform:status: 
  stage: other
  when: manual
  environment:
    name: $ENV