image:
  name: "$NEXUS_REGISTRY/infrastructure/builder:latest"
  entrypoint: [""]
variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"
  TF_VAR_ENV: ${ENV}
  TF_VAR_config: "${CI_PROJECT_DIR}/envs/${ENV}/config.yml"
  TF_VAR_ansible_inventory: "${CI_PROJECT_DIR}/envs/${ENV}/inventory.yml"
  ENV_PATH: ${CI_PROJECT_DIR}/envs/${ENV}

.terraform:status: 
  stage: status
  environment:
    name: $ENV

.terraform:plan: 
  stage: plan
  environment:
    name: $ENV

.terraform:apply: 
  stage: apply
  when: manual
  environment:
    name: $ENV

.ansible:provision: 
  stage: provision
  when: manual
  environment:
    name: $ENV

.terraform:destroy: 
  stage: destroy
  when: manual
  environment:
    name: $ENV

