include:
  - local: gitlab-ci/jobs.yml

default:
  before_script:
    - printenv
    - eval `ssh-agent -s`
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo "$SSH_PUBLIC_KEY"> ~/ya_key.pub
    - source /app/scripts/lib.sh
  tags:
  - infrastructure

stages:
  - status
  - plan
  - apply
  - provision
  - destroy

status.network:
  extends: .terraform:status
  script:
    - terraform_status network
    - yc_get_network

status.hosts:
  extends: .terraform:status
  script:
    - terraform_status hosts
    - yc_get_instances

plan.network:
  extends: .terraform:plan
  script:
    - terraform_plan network

plan.hosts:
  extends: .terraform:plan
  script:
    - terraform_plan hosts

apply.network:
  extends: .terraform:apply
  script:
    - terraform_apply network

apply.hosts:
  extends: .terraform:apply
  script:
    - terraform_apply hosts
  artifacts:
    paths: 
      - ${CI_PROJECT_DIR}/${ENV}/inventory.yml

provision.gitlab:
  extends: .ansible:provision
  script:
    - provision_gitlab
  needs: 
    - job: apply.hosts
      artifacts: true

provision.nexus:
  extends: .ansible:provision
  script:
    - provision_nexus
  needs: 
    - job: apply.hosts
      artifacts: true

destroy.network:
  extends: .terraform:destroy
  script:
    - terraform_destroy network

destroy.hosts:
  extends: .terraform:destroy
  script:
    - terraform_destroy hosts
