workflow:
  rules:
    - if: $ENV
  
include:
  - local: gitlab-ci/jobs.yml

default:
  before_script:
    - echo ${API_KEY} | base64 -d>key.json
    - export YC_SERVICE_ACCOUNT_KEY_FILE=/app/key.json
    - if [ -f "${KUBECONFIG}" ]; then chmod 400 ${KUBECONFIG}; fi;
    - eval `ssh-agent -s`
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo "$SSH_PUBLIC_KEY"> ~/ya_key.pub
    - echo "$ANSIBLE_VAULT_PASSWORD">.vault
    - source /app/scripts/lib.sh
  tags:
  - infrastructure

stages:
  - status
  - plan
  - apply
  - provision
  - destroy

status.network:
  extends: .terraform:status
  script:
    - terraform_status network
    - yc_get_network

status.hosts:
  extends: .terraform:status
  script:
    - terraform_status hosts
    - yc_get_instances

plan.network:
  extends: .terraform:plan
  script:
    - terraform_plan network

plan.hosts:
  extends: .terraform:plan
  script:
    - terraform_plan hosts

apply.network:
  extends: .terraform:apply
  script:
    - terraform_apply network

apply.hosts:
  extends: .terraform:apply
  script:
    - terraform_apply hosts

apply.inventory:
  extends: .terraform:apply
  script:
    - terraform_apply inventory
  artifacts:
    paths: 
      - ${CI_PROJECT_DIR}/envs/${ENV}/inventory.yml

provision.misc:
  extends: .ansible:provision
  script:
    - provision_misc
  needs: 
    - job: apply.inventory
      artifacts: true

provision.gitlab:
  extends: .ansible:provision
  script:
    - provision_gitlab
  needs: 
    - job: apply.inventory
      artifacts: true

provision.infra_repo:
  extends: .ansible:provision
  script:
    - provision_infra_repo
  needs: 
    - job: apply.inventory
      artifacts: true

provision.infra_runner:
  extends: .ansible:provision
  script:
    - provision_infra_runner
  needs: 
    - job: apply.inventory
      artifacts: true

provision.apps_repo:
  extends: .ansible:provision
  script:
    - provision_apps_repo
  needs: 
    - job: apply.inventory
      artifacts: true

provision.nexus:
  extends: .ansible:provision
  script:
    - provision_nexus
  needs: 
    - job: apply.inventory
      artifacts: true

provision.k8s:
  extends: .ansible:provision
  script:
    - provision_k8s
  needs: 
    - job: apply.inventory
      artifacts: true
  artifacts:
    paths: 
      - ${CI_PROJECT_DIR}/envs/${ENV}/artifacts/

provision.k8s_runner:
  extends: .ansible:provision
  script:
    - provision_k8s_runner

provision.monitoring:
  extends: .ansible:provision
  script:
    - provision_monitoring
  needs: 
    - job: apply.inventory
      artifacts: true

destroy.network:
  extends: .terraform:destroy
  script:
    - terraform_destroy network

destroy.hosts:
  extends: .terraform:destroy
  script:
    - terraform_destroy hosts