---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  type: {{ .Values.frontend.service.type }}
  ports: 
  - name: main
    port: 80
    targetPort: 8079
{{- if eq .Values.frontend.service.type "NodePort" }}
    nodePort: {{ .Values.frontend.service.nodePort }}
{{- end }}
  selector:
    name: front-end
