---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    name: payment
spec:
  ports:
    # the port that this service should serve on
  - name: main
    port: 80
    targetPort: {{ .Values.payment.containerPort }}
  selector:
    name: payment
