inventory:
  # ansible inventory structure
  # every host mentioned in this section must be specified in the params: section
  all:
    children:
      gitlab:
        hosts:
          gitlab11:
      nexus:
        hosts:
          nexus11:
  
params:
  cloud_id: b1g8982k5klkcg48dfpf
  folder: devops
  network: instances
  subnets:
    ru-central1-a: [192.168.0.0/24]
    ru-central1-b: [192.168.1.0/24] 
  # hosts specification
  # every host must have defined name, cpu, memory, disk, public_ip
  gitlab11:
    name: gitlab11
    cpu: 2
    memory: 4096
    disk: 40
    zone: ru-central1-b
    public_ip: true
  nexus11:
    name: nexus11
    cpu: 2
    memory: 4096
    disk: 40
    zone: ru-central1-b
    public_ip: true