- name: Boutique Gitlab Runner
  hosts: localhost
  tasks:
    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        name: gitlab
        repo_url: https://charts.gitlab.io
      tags:
        - apps_runner
        - never

    - name: Install kubernetes gitlab-runner
      kubernetes.core.helm:
        name: gitlab-runner
        chart_ref: gitlab/gitlab-runner
        release_namespace: gitlab-runner
        values_files: runner_values.yml
        values:
          runnerRegistrationToken: "{{ token }}"
          gitlabUrl: "{{ url }}"
          runners:
            tags: "{{ env }},k8s"
      tags:
        - apps_runner
        - never

    - name: Check k8s_manifests paths
      stat:
        path: "{{ lookup('env','ENV_PATH') }}//{{ item }}"
      register: stat_results
      with_items: "{{ config.runner.k8s_manifests }}"
      ignore_errors: True
      when: config.runner.k8s_manifests is defined
      tags:
        - apps_runner
        - never

    - name: Apply k8s manifests
      kubernetes.core.k8s:
        namespace: "{{ config.runner.namespace | default('default') }}"
        state: present
        src: "{{ item }}"
      with_items: "{{ stat_results.results | selectattr('stat.exists', 'true') | map(attribute='stat.path') | list }}"
      when: config.runner.enabled is defined and config.runner.enabled | bool
      tags:
        - apps_runner
        - never