
---
- name: Gitlab Group | Boutique | Create
  # https://github.com/ansible-collections/community.general/issues/4990#issuecomment-1193366106
  community.general.gitlab_group:
    api_url: "{{ gitlab_url }}"
    validate_certs: False
    api_username: "{{ gitlab_user }}"
    api_password: "{{ gitlab_password }}"
    name: boutique
    visibility: internal
    description: ''
    project_creation_level: maintainer
    require_two_factor_authentication: no
    subgroup_creation_level: maintainer
    auto_devops_enabled: no
    state: present
  register: gitlab_group
  tags:
  - apps

- name: Gitlab Group | Boutique | Set CI/CD variables
  community.general.gitlab_group_variable:
    api_url: "{{ gitlab_url }}"
    validate_certs: False
    api_username: "{{ gitlab_user }}"
    api_password: "{{ gitlab_password }}"
    group: boutique
    purge: true
    variables: "{{ apps_gitlab_vars }}"
  tags:
  - apps

- name: Gitlab Group | Boutique | Creating Projects
  include_tasks: boutique.yml
  loop: "{{ git_repolist }}"
  tags:
  - never
  - apps

- name: Gitlab Group | Boutique | Waiting for Gitlab runners_token generating
  ansible.builtin.pause:
    seconds: 10
  when: gitlab_group.changed

- name: "Getting runners_token"
  # repeat the same task after delay will return the token
  community.general.gitlab_group:
    api_url: "{{ gitlab_url }}"
    validate_certs: False
    api_username: "{{ gitlab_user }}"
    api_password: "{{ gitlab_password }}"
    name: boutique
    visibility: internal
    description: ''
    project_creation_level: maintainer
    require_two_factor_authentication: no
    subgroup_creation_level: maintainer
    auto_devops_enabled: no
    state: present
  register: gitlab_apps_group
  tags:
  - apps
  - apps_runner

- name: Gitlab Group | Boutique | Save runner token
  ansible.builtin.set_fact:
    apps_runner_token: "{{ gitlab_apps_group.group.runners_token }}"
    gitlab_url: "{{ gitlab_url }}"
  tags:
  - apps
  - apps_runner