inventory:
  # ansible inventory structure
  # every host mentioned in this section must be specified in the params: section
  all:
    children:
      k8s_cluster:
        children:
          kube_node:
            hosts:
              master11:  
              master12:
          kube_control_plane:
            hosts:
              master11: 
              master12:
          etcd:
            hosts:
              master11: 
              master12:
  
# hosts specification
# every host must have defined name, cpu, memory, disk, public_ip
hosts:
  master11:
    name: master11
    cpu: 2
    memory: 4096
    disk: 40
    subnet: subnet-a
    public_ip: true
  master12:
    name: master12
    cpu: 2
    memory: 4096
    disk: 40
    subnet: subnet-b
    public_ip: true