inventory:
  # ansible inventory structure
  # every host mentioned in this section must be specified in the params: section
  all:
    children:
      k8s_cluster:
        children:
          kube_node:
            hosts:
              worker-dev11:  
              worker-dev12:
          kube_control_plane:
            hosts:
              master-dev13: 
          etcd:
            hosts:
              master-dev13: 
  
# hosts specification
# every host must have defined name, cpu, memory, disk, public_ip
hosts:
  worker-dev11:
    name: worker-dev11
    cpu: 2
    memory: 2048
    disk: 40
    subnet: dev-a
    public_ip: true
  worker-dev12:
    name: worker-dev12
    cpu: 2
    memory: 2048
    disk: 40
    subnet: dev-b
    public_ip: true
  master-dev13:
    name: master-dev13
    cpu: 2
    memory: 2048
    disk: 40
    subnet: dev-b
    public_ip: true